# Generated by Django 4.2.1 on 2023-06-04 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='start_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination_city',
            field=models.CharField(choices=[('casablanca', 'Casablanca'), ('marrakech', 'Marrakech'), ('fes', 'Fes'), ('tangier', 'Tangier')], max_length=12, verbose_name='Destination City'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_city',
            field=models.CharField(choices=[('casablanca', 'Casablanca'), ('marrakech', 'Marrakech'), ('fes', 'Fes'), ('tangier', 'Tangier')], max_length=12, verbose_name='Start City'),
        ),
    ]
